extraction:
  cpp:
    prepare:
      packages:
      - autoconf
      - autoconf-archive
      - automake
      - ca-certificates
      - file
      - libtool
      - make
      - pkg-config
      - libdispatch-dev
      - libibumad-dev
      - libpciaccess-dev
      - libssh-dev
      - libpci-dev
    configure:
      command:
      - autoreconf -fiv
      - ./configure
    index:
      build_command: make -j$(nproc)
