name: Code coverage 

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y autoconf autoconf-archive automake ca-certificates file gnupg lcov libtool make pkg-config libdispatch-dev libibumad-dev libopenmpi-dev libpciaccess-dev libssh-dev openmpi-bin openssh-client pciutils-dev software-properties-common wget
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
        sudo add-apt-repository "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"
        sudo apt-get update -y
        sudo apt-get install -y cuda-nvml-dev-10-1
        echo "::set-env name=CPATH::/usr/local/cuda-10.1/targets/x86_64-linux/include:$CPATH"

    - name: autogen
      run: ./autogen.sh

    - name: configure
      run: ./configure --enable-code-coverage

    - name: make
      run: make -j$(nproc)

    - name: make check-code-coverage
      run: CODE_COVERAGE_OUTPUT_FILE=wassail-coverage.info VERBOSE=1 make check-code-coverage -j$(nproc)

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./wassail-coverage.info
