name: Linux build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y autoconf autoconf-archive automake ca-certificates file gnupg libtool make pkg-config libdispatch-dev libibumad-dev libpciaccess-dev libssh-dev pciutils-dev software-properties-common wget
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
        sudo add-apt-repository "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"
        sudo apt-get update -y
        sudo apt-get install -y cuda-nvml-dev-10-1
        echo "::set-env name=CPATH::/usr/local/cuda-10.1/targets/x86_64-linux/include:$CPATH"

    - name: autoreconf
      run: autoreconf -fiv

    - name: configure
      run: ./configure

    - name: make
      run: make -j$(nproc)

    - name: make check
      run: VERBOSE=1 make check -j$(nproc)

    - name: make install
      run: sudo make install

    - name: make installcheck
      run: LD_LIBRARY_PATH=/usr/local/lib make installcheck
