name: Linux build

on: push

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
        compiler: [gcc, clang]
        mpi: [mpich, openmpi]
    
    steps:
    - uses: actions/checkout@v6

    - name: install dependencies
      run: |
        sudo apt-get update -y
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y autoconf autoconf-archive automake ca-certificates file gnupg libtool make pkg-config libibumad-dev libpciaccess-dev libssh-dev libudev-dev openssh-client software-properties-common wget
        if [ "${{ matrix.mpi }}" = "mpich" ]; then
          sudo apt-get install -y libmpich-dev mpich
        else
          sudo apt-get install -y libopenmpi-dev openmpi-bin
        fi
        if [ "${{ matrix.os }}" = "ubuntu-26.04" ]; then
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2604/x86_64/cuda-keyring_1.1-1_all.deb
        elif [ "${{ matrix.os }}" = "ubuntu-24.04" ]; then
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
        elif [ "${{ matrix.os }}" = "ubuntu-22.04" ]; then
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
        fi
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt-get update -y
        sudo apt-get install -y cuda-nvml-dev-13-1
        echo "CPATH=/usr/local/cuda-13.1/include:$CPATH" >> $GITHUB_ENV

    - name: set compiler
      run: |
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
        else
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
        fi

    - name: autogen
      run: ./autogen.sh

    - name: configure
      run: ./configure

    - name: make
      run: make -j$(nproc)

    - name: make check
      run: VERBOSE=1 make check -j$(nproc)

    - name: make install
      run: sudo make install

    - name: make installcheck
      run: LD_LIBRARY_PATH=/usr/local/lib make installcheck
