name: macOS build

on: push

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: brew install autoconf autoconf-archive automake libtool

    - name: autogen
      run: ./autogen.sh

    - name: configure
      run: ./configure

    - name: make
      run: make -j$(sysctl -n hw.physicalcpu)

    - name: make check
      run: VERBOSE=1 make check -j$(sysctl -n hw.physicalcpu)

    - name: make install
      run: sudo make install

    - name: make installcheck
      run: make installcheck
