name: macOS build

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: brew install autoconf autoconf-archive automake libtool

    - name: autoreconf
      run: autoreconf -fiv

    - name: configure
      run: ./configure

    - name: make
      run: make -j$(nproc)

    - name: make check
      run: VERBOSE=1 make check -j$(nproc)

    - name: make distcheck
      run: make distcheck
